import React from 'react';
import { siteConfig } from '@/config/site';
import { createMetadata, generateBreadcrumbSchema } from '@/lib/seo';
import { Breadcrumbs } from '@/components/layout/Breadcrumbs';
import { Scale, ShieldAlert, FileText, CheckCircle2, Lock, AlertTriangle, Hammer } from 'lucide-react';
import type { Metadata } from 'next';

export const metadata = createMetadata({
  title: 'Terms of Service & Usage Agreement',
  description: 'CraftCalc terms of service, material estimation disclaimers, intellectual property rules, and acceptable usage guidelines.',
  path: '/terms'
});

export default function TermsPage() {
  const breadcrumbSchema = generateBreadcrumbSchema([
    { name: 'Home', item: '/' },
    { name: 'Terms of Service', item: '/terms' },
  ]);

  return (
    <div className="min-h-screen bg-slate-50/50 pb-16">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pt-4">
        <Breadcrumbs items={[{ name: 'Terms of Service', href: '/terms' }]} />

        <div className="my-8 p-6 sm:p-10 rounded-2xl bg-white border border-slate-200 shadow-sm space-y-8 text-slate-700 text-sm leading-relaxed">
          <header className="border-b border-slate-100 pb-4 space-y-1">
            <div className="flex items-center gap-2 text-emerald-600 text-xs font-bold uppercase tracking-wider">
              <Scale className="w-4 h-4" />
              <span>Legal Agreement</span>
            </div>
            <h1 className="text-2xl sm:text-3xl font-black text-slate-900 tracking-tight">
              Terms of Service & Platform Usage Agreement
            </h1>
            <p className="text-xs text-slate-400">Effective Date: August 2026 | Version 2.5 | Last Updated: August 2026</p>
          </header>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2">
              <FileText className="w-4 h-4 text-emerald-600" />
              1. Acceptance of Terms
            </h2>
            <p>
              Welcome to CraftCalc ({siteConfig.url}). By accessing, browsing, registering for, or otherwise using any interactive estimation calculator, reference matrix, or educational guide provided on our website, you acknowledge that you have read, understood, and agree to be legally bound by these Terms of Service, along with our Privacy Policy and Material Disclaimer.
            </p>
            <p>
              If you do not agree to all terms and conditions contained herein, you must immediately terminate your use of this service. We reserve the right to revise and modify these Terms at any time without prior individual notice by publishing an updated revision date.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2">
              <Hammer className="w-4 h-4 text-emerald-600" />
              2. Nature of Estimation Calculators & Professional Disclaimer
            </h2>
            <p>
              CraftCalc produces mathematical calculation models, waste percentage recommendations, unit conversions, and construction planning tools designed exclusively for general educational, estimation, and preliminary planning purposes.
            </p>
            <p>
              Calculations generated by our software do not constitute certified architectural blueprints, structural engineering calculations, building code approvals, or formal contractor bids. Physical job site conditions—including subfloor unlevelness, wall deflection, temperature fluctuations, and manufacturer batch discrepancies—frequently cause real-world material yields to deviate from standard theoretical values.
            </p>
            <p>
              Users are strictly advised to physically verify all on-site measurements with calibrated measuring instruments and to consult a licensed, insured general contractor or structural engineer prior to cutting materials, signing construction contracts, or placing non-returnable bulk orders.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2">
              <Lock className="w-4 h-4 text-emerald-600" />
              3. Intellectual Property Rights & Acceptable Usage
            </h2>
            <p>
              All proprietary algorithms, client-side software code, user interface designs, mathematical formulas, trade matrices, graphics, logos, and original educational articles published across CraftCalc are the exclusive intellectual property of CraftCalc and are protected by applicable copyright, trademark, and trade secret laws.
            </p>
            <p>
              We grant you a personal, limited, non-exclusive, revocable license to access and use our calculators for non-commercial and internal business estimating purposes. You agree that you will not:
            </p>
            <ul className="list-disc list-inside space-y-1 pl-2 text-xs sm:text-sm text-slate-600">
              <li>Use automated web crawlers, bots, or scrapers to extract our proprietary calculation engines or database registries.</li>
              <li>Decompile, reverse engineer, disassemble, or attempt to derive the source code of our interactive calculators.</li>
              <li>Re-host, frame, white-label, or sell our tools as standalone commercial software without explicit written permission.</li>
              <li>Transmit any malicious code, virus, or automated denial-of-service payload to our servers or edge networks.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2">
              <AlertTriangle className="w-4 h-4 text-emerald-600" />
              4. Limitation of Liability & Warranty Disclaimers
            </h2>
            <p>
              To the fullest extent permitted by applicable law, CraftCalc, its founders, contributors, editorial panel, and technical partners provide all services on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis without warranties of any kind, whether express, implied, statutory, or otherwise.
            </p>
            <p>
              Under no circumstances shall CraftCalc or its representatives be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising out of your use of our calculators—including, but not limited to, material shortfalls, project delays, structural failures, demolition expenses, or excess inventory losses.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2">
              <Scale className="w-4 h-4 text-emerald-600" />
              5. Governing Law, Severability & Contact
            </h2>
            <p>
              These Terms shall be governed by and construed in accordance with applicable statutory trade and commercial laws. If any provision of these Terms is deemed unlawful, void, or unenforceable, that provision shall be deemed severable and shall not affect the validity and enforceability of any remaining provisions.
            </p>
            <p>
              For legal inquiries, copyright licensing requests, or formal communications regarding these Terms, please contact our legal counsel via email at <strong>{siteConfig.author.email}</strong>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
